### ISSUE TITLE
What do the 12 bytes at the beginning of the data packet represent?

### ISSUE THREAD

**Issue by nijinekoyo** [rafi1212122/SCHALE.GameServer#1]
I noticed that the [GatewayController.cs#L39](https://github.com/rafi1212122/SCHALE.GameServer/blob/master/SCHALE.GameServer/Controllers/Api/GatewayController.cs#L39) code skipped 12 bytes when reading the data packet. The comment stated that it was `CRC + Protocol type conversion + payload length`, but I didn’t quite understand what these 12 bytes represented. , could you please tell me their specific functions and construction methods?

**Comment by rafi1212122** [comment]
- CRC is the packet hash (iirc not actually CRC32 but still 4 bytes long).
- TypeConversion is I believe their internal corresponding packet type by number, the values are obfuscated in reality so I didn't use it.
- PayloadLength as the name suggests is the rest of the payload length outside the header, not important in this context since it's already guaranteed because that is in the http context.

**Comment by nijinekoyo** [comment]
Well, because I'm trying to implement a third-party client, I want to know more detailed information about these 12 bytes.
1. Whether the CRC calculates the content before encryption or the content after encryption. If not CRC32, what is the calculation method?
2. How many bytes is the length of TypeConversion?
3. PayloadLength is calculated based on the content before or after encryption.

Thank you very much for your help

**Comment by rafi1212122** [comment]
1. Figure it out yourself by the client, i don't have much time to figure that out so i ignored it.
2. All three of those are 4 bytes each, that's why it's 12.
3. The encryption used is symmetrical iirc, but i don't remember if there's a compression method.

**Comment by nijinekoyo** [comment]
I see
Thank you so much
